<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["posts", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit posts
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "posts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBody" class="col-sm-2 control-label">Body</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["body", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldBody"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSlug" class="col-sm-2 control-label">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["slug", "size" => 30, "class" => "form-control", "id" => "fieldSlug"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAuthorId" class="col-sm-2 control-label">Author</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["author_id", "type" => "number", "class" => "form-control", "id" => "fieldAuthorId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPostTypeId" class="col-sm-2 control-label">Post Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["post_type_id", "type" => "number", "class" => "form-control", "id" => "fieldPostTypeId"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
