<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search posts
    </h1>
    <p>
		<?php echo $this->tag->linkTo( [ "posts/new", "Create posts" ] ) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Body</th>
            <th>Slug</th>
            <th>Author</th>
            <th>Post Of Type</th>
            <th>Categories</th>


        </tr>
        </thead>
        <tbody>
		<?php foreach ( $posts as $post ): ?>
            <tr>
                <td><?php echo $post->id ?></td>
                <td><?php echo $post->title ?></td>
                <td><?php echo $post->body ?></td>
                <td><?php echo $post->slug ?></td>
                <td><?php echo $post->Authors->name_f_l ?></td>
                <td><?php echo $post->PostTypes->name ?></td>
                <td><?php
	                $aCat = array();
					foreach ( $post->PostCategories2 as $cat ) {
						//echo $cat;
						$aCat[] = $cat->name;
					}
					echo implode(', ',$aCat);
					?></td>


            </tr>
		<?php endforeach; ?>
        </tbody>
    </table>
</div>

