<?php

/**
 * Authors
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-18, 23:25:18
 */
class Authors extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $name_f_l;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("admin_pte");
        $this->hasMany('id', 'Posts', 'author_id', ['alias' => 'Posts']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'authors';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Authors[]|Authors
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Authors
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
