<?php

/**
 * Posts
 *
 * @autogenerated by Phalcon Developer Tools
 * @date          2017-06-19, 12:53:09
 */
class Posts extends \Phalcon\Mvc\Model {

	/**
	 *
	 * @var integer
	 * @Primary
	 * @Column(type="integer", length=11, nullable=false)
	 */
	public $id;

	/**
	 *
	 * @var string
	 * @Column(type="string", length=45, nullable=true)
	 */
	public $title;

	/**
	 *
	 * @var string
	 * @Column(type="string", nullable=true)
	 */
	public $body;

	/**
	 *
	 * @var string
	 * @Column(type="string", length=45, nullable=true)
	 */
	public $slug;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=11, nullable=false)
	 */
	public $author_id;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=11, nullable=false)
	 */
	public $post_type_id;

	/**
	 * Initialize method for model.
	 */
	public function initialize() {
		$this->setSchema( "admin_pte" );
		$this->hasMany('id', 'PostCategories', 'posts_id', ['alias' => 'PostCategories']);
		$this->hasManyToMany( 'id', 'PostCategories', 'posts_id', 'categories_id', 'Categories', 'id', [ 'alias' => 'PostCategories2' ] );
		$this->belongsTo( 'author_id', '\Authors', 'id', [ 'alias' => 'Authors' ] );
		$this->belongsTo( 'post_type_id', '\PostTypes', 'id', [ 'alias' => 'PostTypes' ] );
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource() {
		return 'posts';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 *
	 * @return Posts[]|Posts
	 */
	public static function find( $parameters = NULL ) {
		return parent::find( $parameters );
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 *
	 * @return Posts
	 */
	public static function findFirst( $parameters = NULL ) {
		return parent::findFirst( $parameters );
	}

}
