<?php

/**
 * PostCategories
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-19, 12:52:50
 */
class PostCategories extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $posts_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $categories_id;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("admin_pte");
        $this->belongsTo('categories_id', '\Categories', 'id', ['alias' => 'Categories']);
        $this->belongsTo('posts_id', '\Posts', 'id', ['alias' => 'Posts']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'post_categories';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return PostCategories[]|PostCategories
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return PostCategories
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
